import 'package:flutter/material.dart';
import '../data/theme_data.dart';

class Playlist with ChangeNotifier {
  // id randomly generated by Firebase
  String id = '';
  // the name of the playlist, provided by the user
  String name = '';
  // the userId of the user that created the playlist
  String createdBy = '';
  // the tips in the playlist (list of tipId)
  List<dynamic> listOfTipsId = [];
  // the users in the playlist (list of UserId)
  List<dynamic> listOfUsersId = [];
  String? imageUrl;
  String? imageTipId;
  String? playlistPrivacy;
  List<String>? visibleToUserIds = [];
  String playlistStatus = 'active';
  String? timeStampCreated;

  Playlist({
    required this.id,
    required this.name,
    required this.createdBy,
    required this.listOfTipsId,
    required this.listOfUsersId,
    required this.playlistStatus,
    required this.timeStampCreated,
    this.imageUrl,
    this.imageTipId,
    this.playlistPrivacy,
    this.visibleToUserIds,
  });

  set setPlaylistId(String newId) {
    id = newId;
  }

  /// We will use this method to use pagination. Unfortunately with pagination we need
  /// to cast all the objects in a list, e.g. the list of user Id we send the tip to is stored
  /// as a list of strings, and returns to use as a list of items that are strings, but
  /// is read as a list of dynamic objects.
  Playlist.fromJson(Map<String, dynamic> json) {
    List<String> listOfUsersIdAsStrings = [];
    for (var sentToString in json['listOfUsersId']) {
      listOfUsersIdAsStrings.add(sentToString);
    }
    List<String> visibleToAsStrings = [];
    if (json.containsKey('visibleToUserIds'))
      for (var visibleToString in json['visibleToUserIds']) {
        visibleToAsStrings.add(visibleToString);
      }
// we will fill the id using a setter method when we fetch the playlist with pagination
    id = '';
    name = json['name'];
    createdBy = json.containsKey('createdBy') ? json['createdBy'] : '';
    listOfTipsId = json['listOfTipsId'];
    listOfUsersId = json['listOfUsersId'];
    imageUrl = json.containsKey('imageUrl') ? json['imageUrl'] : null;
    imageTipId = json.containsKey('imageTipId') ? json['imageTipId'] : null;
    playlistPrivacy = json.containsKey('playlistPrivacy')
        ? json['playlistPrivacy']
        //if legacy playlist choose privacy based on listOfUsersId length
        : listOfUsersIdAsStrings.length == 1
            ? constPlaylistPrivacyPrivate
            : constPlaylistPrivacyTaggedFriends;
    //check if visibleTo field available
    visibleToUserIds = json.containsKey('visibleToUserIds')
        ? visibleToAsStrings
        //if legacy tip fill in with sentTo
        : listOfUsersIdAsStrings;
    playlistStatus = json.containsKey('playlistStatus')
        ? json['playlistStatus']
        //if legacy playlist choose privacy based on listOfUsersId length
        : listOfUsersIdAsStrings.isEmpty
            ? constPlaylistStatusDeleted
            : constPlaylistStatusActive;
    timeStampCreated = json.containsKey('timeStampCreated')
        ? json['timeStampCreated']
        //if legacy playlist choose privacy based on listOfUsersId length
        : DateTime.now().toUtc().toString();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();

    return data;
  }
}
