// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9i9aRR9hf-r4Za-h2BX03uk0_pzZ7gUw',
    appId: '1:124802101281:web:7140f5a40ee4d8a5d63360',
    messagingSenderId: '124802101281',
    projectId: 'storywood-34d40',
    authDomain: 'storywood-34d40.firebaseapp.com',
    databaseURL:
        'https://storywood-34d40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'storywood-34d40.appspot.com',
    measurementId: 'G-P524SJMYQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw4Z0h5PCnYPbL2ZV5ilWtYYsl6ycG_bc',
    appId: '1:124802101281:android:f62130d1055adbe8d63360',
    messagingSenderId: '124802101281',
    projectId: 'storywood-34d40',
    databaseURL:
        'https://storywood-34d40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'storywood-34d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpV56Ikxblp61HMNZ9fd5D6tVNJLAiFDU',
    appId: '1:124802101281:ios:c0116a4ed911ca1dd63360',
    messagingSenderId: '124802101281',
    projectId: 'storywood-34d40',
    databaseURL:
        'https://storywood-34d40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'storywood-34d40.appspot.com',
    iosClientId:
        '124802101281-rd8a0q0c33sbkhtpr75bpqitnru954tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.storywoodMvp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpV56Ikxblp61HMNZ9fd5D6tVNJLAiFDU',
    appId: '1:124802101281:ios:c0116a4ed911ca1dd63360',
    messagingSenderId: '124802101281',
    projectId: 'storywood-34d40',
    databaseURL:
        'https://storywood-34d40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'storywood-34d40.appspot.com',
    iosClientId:
        '124802101281-rd8a0q0c33sbkhtpr75bpqitnru954tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.storywoodMvp01',
  );
}
